name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run test:ci

  secrets:
    name: Secrets detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for secrets with Gitleaks
        run: docker run --rm -v "$GITHUB_WORKSPACE":/path zricethezav/gitleaks:latest detect --source /path --verbose --redact --exit-code 1
